title: "&f[&a空岛战争&f]"

scoreboard-title: "&a空岛战争"

# 是否保存玩家背包
save-playerInventory:  true

# 是否启用房间录制和回放
enable-Record: true


game-logo: "author: sobadfish "

join-menu:
  cw:
    buttonImg:
      type: "path"
      path: "textures/ui/icon_recipe_item"
    rooms:
      - 测试房间